name: Build Open Graph Images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv
          tools: composer:v2
          
      - name: Set Up Project
        run: ./bin/setup.sh

      - name: Set Up Chrome Driver
        uses: nanasess/setup-chromedriver@v1

      - name: Start Chrome Driver
        run: |
          export DISPLAY=:99
          chromedriver --port=4444 &
          sudo Xvfb -ac :99 -screen 0 1400x1200x24 > /dev/null 2>&1 &

      - name: Start Laravel Server
        env:
          TORCHLIGHT_HOST: ${{ secrets.TORCHLIGHT_HOST }}
          TORCHLIGHT_TOKEN: ${{ secrets.TORCHLIGHT_TOKEN }}
        run: php artisan serve --no-reload &

      - name: Generate Open Graph Images
        env:
          TORCHLIGHT_HOST: ${{ secrets.TORCHLIGHT_HOST }}
          TORCHLIGHT_TOKEN: ${{ secrets.TORCHLIGHT_TOKEN }}
          APP_ENV: local
          APP_URL: http://127.0.0.1:8000/
        run: php artisan og:generate-images

      - name: Commit Open Graph Images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'public/img/og/*.png'
          commit_message: Add open graph images
